name 'NodeJSApp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures blog_refactor_nodejs'
long_description 'Installs/Configures blog_refactor_nodejs'
issues_url 'https://github.com/stelligent/blog_refactor_nodejs/issues'
source_url 'https://github.com/stelligent/blog_refactor_nodejs'
version '0.1.0'

depends 'apt'
#depends 'chef_cfn', '~> 1.0.0'
depends 'nodejs', '~> 2.4.4'
